#include "devicesimulatorwindow.h"
#include "shared/protocol/jsonlinecodec.h"
#include <QTcpSocket>
#include <QTimer>
#include <QLineEdit>
#include <QLabel>
#include <QTextEdit>
#include <QPushButton>
#include <QGridLayout>
#include <QVBoxLayout>
#include <QJsonDocument>
#include <QDateTime>
#include <QUuid>

DeviceSimulatorWindow::DeviceSimulatorWindow():m_socket(new QTcpSocket(this)),m_heartbeat(new QTimer(this)),m_telemetry(new QTimer(this)),m_reconnect(new QTimer(this)){setWindowTitle(QStringLiteral("EVCharge Device Simulator"));auto *r=new QVBoxLayout(this);auto *g=new QGridLayout; m_host=new QLineEdit(QStringLiteral("127.0.0.1"));m_port=new QLineEdit(QStringLiteral("18082"));m_pileId=new QLineEdit(QStringLiteral("4"));m_pileNo=new QLineEdit(QStringLiteral("ST001-P04"));const QList<QPair<QString,QLineEdit*>> fs={{QStringLiteral("Server Host"),m_host},{QStringLiteral("Device Port"),m_port},{QStringLiteral("pileId"),m_pileId},{QStringLiteral("pileNo"),m_pileNo}};int row=0;for(const auto &f:fs){g->addWidget(new QLabel(f.first),row,0);g->addWidget(f.second,row++,1);}auto *c=new QPushButton(QStringLiteral("Connect")),*d=new QPushButton(QStringLiteral("Disconnect"));g->addWidget(c,row,0);g->addWidget(d,row,1);r->addLayout(g);m_state=new QLabel; m_values=new QLabel;r->addWidget(m_state);r->addWidget(m_values);auto *fault=new QPushButton(QStringLiteral("Inject TEMP_HIGH")),*cut=new QPushButton(QStringLiteral("通信中断")),*restore=new QPushButton(QStringLiteral("恢复通信"));r->addWidget(fault);r->addWidget(cut);r->addWidget(restore);m_log=new QTextEdit;m_log->setReadOnly(true);r->addWidget(m_log,1);connect(c,&QPushButton::clicked,this,&DeviceSimulatorWindow::connectDevice);connect(d,&QPushButton::clicked,this,&DeviceSimulatorWindow::disconnectDevice);connect(m_socket,&QTcpSocket::connected,this,&DeviceSimulatorWindow::connected);connect(m_socket,&QTcpSocket::readyRead,this,&DeviceSimulatorWindow::read);connect(m_heartbeat,&QTimer::timeout,this,&DeviceSimulatorWindow::heartbeat);connect(m_telemetry,&QTimer::timeout,this,&DeviceSimulatorWindow::telemetry);connect(fault,&QPushButton::clicked,this,&DeviceSimulatorWindow::injectFault);connect(cut,&QPushButton::clicked,this,&DeviceSimulatorWindow::disconnectFault);connect(restore,&QPushButton::clicked,this,&DeviceSimulatorWindow::reconnect);m_heartbeat->setInterval(2000);m_telemetry->setInterval(1000);m_reconnect->setSingleShot(true);connect(m_reconnect,&QTimer::timeout,this,&DeviceSimulatorWindow::connectDevice);}
void DeviceSimulatorWindow::connectDevice(){m_simulateCut=false;if(m_socket->state()!=QAbstractSocket::UnconnectedState)return;m_socket->connectToHost(m_host->text(),m_port->text().toUShort());}
void DeviceSimulatorWindow::connected(){send({{QStringLiteral("type"),QStringLiteral("DEVICE_HELLO")},{QStringLiteral("messageId"),QUuid::createUuid().toString(QUuid::WithoutBraces)},{QStringLiteral("pileId"),m_pileId->text().toLongLong()},{QStringLiteral("pileNo"),m_pileNo->text()},{QStringLiteral("protocolVersion"),QStringLiteral("1.0")},{QStringLiteral("simulatorVersion"),QStringLiteral("1.0")}});m_heartbeat->start();m_telemetry->start();log(QStringLiteral("TX HELLO"));}
void DeviceSimulatorWindow::disconnectDevice(){m_heartbeat->stop();m_telemetry->stop();m_socket->disconnectFromHost();}
void DeviceSimulatorWindow::send(const QJsonObject&m){if(m_socket->state()==QAbstractSocket::ConnectedState)m_socket->write(JsonLineCodec::encode(m));}
void DeviceSimulatorWindow::read(){while(m_socket->canReadLine()){const auto m=QJsonDocument::fromJson(m_socket->readLine()).object();log(QStringLiteral("RX ")+m.value(QStringLiteral("type")).toString());if(m.value(QStringLiteral("type")).toString()==QStringLiteral("DEVICE_COMMAND"))command(m);}}
void DeviceSimulatorWindow::command(const QJsonObject&m){const QString c=m.value(QStringLiteral("command")).toString();if(c==QStringLiteral("START_CHARGING"))m_deviceState=QStringLiteral("CHARGING");else if(c==QStringLiteral("STOP_CHARGING"))m_deviceState=QStringLiteral("AVAILABLE");else if(c==QStringLiteral("RESTART")){m_deviceState=QStringLiteral("RESTARTING");QTimer::singleShot(1500,this,[this,m]{m_fault.clear();m_deviceState=QStringLiteral("AVAILABLE");send({{QStringLiteral("type"),QStringLiteral("DEVICE_ACK")},{QStringLiteral("commandId"),m.value(QStringLiteral("commandId"))},{QStringLiteral("pileId"),m_pileId->text().toLongLong()},{QStringLiteral("command"),QStringLiteral("RESTART")},{QStringLiteral("success"),true},{QStringLiteral("message"),QStringLiteral("restart complete")}});});return;}send({{QStringLiteral("type"),QStringLiteral("DEVICE_ACK")},{QStringLiteral("commandId"),m.value(QStringLiteral("commandId"))},{QStringLiteral("pileId"),m_pileId->text().toLongLong()},{QStringLiteral("command"),c},{QStringLiteral("success"),true},{QStringLiteral("message"),QStringLiteral("ok")}});}
void DeviceSimulatorWindow::heartbeat(){send({{QStringLiteral("type"),QStringLiteral("DEVICE_HEARTBEAT")},{QStringLiteral("pileId"),m_pileId->text().toLongLong()}});}
void DeviceSimulatorWindow::telemetry(){double p=m_deviceState==QStringLiteral("CHARGING")?m_rated*0.94:0;if(p)m_energy+=p/3600.;m_values->setText(QStringLiteral("%1 | %2 kW | %3 kWh").arg(m_deviceState).arg(p,0,'f',1).arg(m_energy,0,'f',3));send({{QStringLiteral("type"),QStringLiteral("DEVICE_TELEMETRY")},{QStringLiteral("pileId"),m_pileId->text().toLongLong()},{QStringLiteral("powerKw"),p},{QStringLiteral("voltageV"),p?380:0},{QStringLiteral("currentA"),p?150:0},{QStringLiteral("temperatureC"),m_fault.isEmpty()?31:95},{QStringLiteral("sessionEnergyKwh"),m_energy},{QStringLiteral("timestamp"),QDateTime::currentDateTime().toString(Qt::ISODate)}});}
void DeviceSimulatorWindow::injectFault(){m_fault=QStringLiteral("TEMP_HIGH");m_deviceState=QStringLiteral("FAULT");send({{QStringLiteral("type"),QStringLiteral("DEVICE_STATUS")},{QStringLiteral("pileId"),m_pileId->text().toLongLong()},{QStringLiteral("status"),QStringLiteral("FAULT")},{QStringLiteral("faultCode"),m_fault},{QStringLiteral("faultMessage"),QStringLiteral("simulated high temperature")}});log(QStringLiteral("TX FAULT"));}
void DeviceSimulatorWindow::disconnectFault(){m_simulateCut=true;disconnectDevice();log(QStringLiteral("communication interrupted"));}
void DeviceSimulatorWindow::reconnect(){m_simulateCut=false;m_reconnect->start(1000);}
void DeviceSimulatorWindow::log(const QString&s){m_log->append(QDateTime::currentDateTime().toString(QStringLiteral("hh:mm:ss "))+s);}
